chat-spaceの非同期通信の実装
kurayoshi981/chatspace pull request #2
Opened 2019-01-21 07:16 UTC by kurayoshi981

#WHAT
chat-spaceの非同期通信の実装

#WHY
非同期で通信ができてるのかを確認するため

2019-01-21 07:43 UTC, takebn26 requested changes

2019-01-21 07:43 UTC, takebn26 commented on Gemfile
> +  gem 'erb2haml'
gem 'erb2haml'
はdevelopment環境でのみ使うものなので記述場所を変えましょう

2019-01-21 07:43 UTC, takebn26 commented on Gemfile
> +
ここから上のgemのインデントは
57行目と合わせましょう

2019-01-21 07:43 UTC, takebn26 commented on app/assets/javascripts/message.js
> +                        <p class="lower-message__content">${message.content }</p>
細かいですが
${message.content }
contentの後の半角消しましょう
こういったことを気をつけることでよりコードが綺麗になります

2019-01-21 07:43 UTC, takebn26 commented on app/assets/javascripts/message.js
> +      $('.messages').append(html);
message欄だったり
画像が残ったままになっていませんか？

2019-01-21 07:43 UTC, takebn26 commented on app/assets/stylesheets/application.scss
> +// @import "config/size";
コメントアウトいらない場合は消しましょう

2019-01-21 07:43 UTC, takebn26 commented on app/assets/stylesheets/modules/group.scss
> +  h1 {
要素自体にcssを書くと拡張性がなくなっていきます
classを当ててそこに書くようにしましょう

2019-01-21 07:43 UTC, takebn26 commented on spec/models/message_spec.rb
> +      it 'is valid with content' do
imageとmessage両方ない場合の処理はどうなるでしょうか

2019-01-21 07:43 UTC, takebn26 commented on config/initializers/devise.rb
> +  config.password_length = 6..128
passwordをdeviseの設定から8文字にしましょう

2019-01-21 07:43 UTC, takebn26 commented on app/views/messages/index.html.haml
> +    = render partial: 'message', collection: @messages
render @messages
だけでもいけませんか？

2019-01-21 07:43 UTC, takebn26 commented on app/views/messages/index.html.haml
> +        グループ名が表示される
グループ名が表示できるようにしましょう

2019-01-21 07:43 UTC, takebn26 commented on app/views/messages/index.html.haml
> +        メンバー名が表示される
メンバーが表示できるようにしましょう

2019-01-21 07:43 UTC, takebn26 commented
viewのスクリーンショットをそれぞれ送っていただけるとありがたいです！

2019-01-21 08:22 UTC, kurayoshi981 commented on Gemfile
> +  gem 'erb2haml'
修正しました！

2019-01-21 08:22 UTC, kurayoshi981 commented on Gemfile
> +
修正しました！

2019-01-21 08:23 UTC, kurayoshi981 commented on app/assets/javascripts/message.js
> +                        <p class="lower-message__content">${message.content }</p>
修正しました！
こういう細かい指摘はありがたいです！

2019-01-21 08:23 UTC, kurayoshi981 commented on app/assets/stylesheets/application.scss
> +// @import "config/size";
修正しました！

2019-01-21 08:25 UTC, kurayoshi981 commented on config/initializers/devise.rb
> +  config.password_length = 6..128
修正しました！

2019-01-21 08:35 UTC, kurayoshi981 commented on app/views/messages/index.html.haml
> +    = render partial: 'message', collection: @messages
いけました！

2019-01-22 05:03 UTC, kurayoshi981 commented on app/views/messages/index.html.haml
> +        グループ名が表示される
修正しました！

2019-01-22 05:03 UTC, kurayoshi981 commented on app/views/messages/index.html.haml
> +        メンバー名が表示される
修正しました！

2019-01-22 13:37 UTC, kurayoshi981 commented
#WHAT
 非同期通信の指摘箇所の修正

#WHY
　実装のため

#GIF
https://gyazo.com/c6f566bae6d44b8f0e5f8400ae41df9a

2019-01-23 02:03 UTC, hzak2xx approved these changes
LGTMです

2019-01-26 06:33 UTC, merged